name: Build & Test

#on:
  #pull_request:
    #branches: [main]
  #push:
    #branches: [main]

on:
  workflow_dispatch:  # Allows manual execution from GitHub UI	
  
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test

      - name: Generate .env file from GitHub Secrets
        run: |
          echo "${{ secrets.ENV_VARS }}" > $GITHUB_WORKSPACE/.env
          
      # Optional: Verify file content
      - name: Debug - Check if .env exists
        run: cat $GITHUB_WORKSPACE/.env
        
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            ${{ github.workspace }}/.env
            ${{ github.workspace }}/target/*.jar
            ${{ github.workspace }}/Dockerfile
            ${{ github.workspace }}/docker-compose.yml
            ${{ github.workspace }}/src/main/resources/application*.properties
          include-hidden-files: true
      - name: List Uploaded Artifacts
        run: ls -R ${{ github.workspace }}
        
      - name: Send Success Notification (Slack)
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "✅ Build & Tests Passed!"
          
      - name: Send Failure Notification (Slack)
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "❌ Build Failed! Check logs."
    
      - name: Send Email Notification
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Build & Tests Passed!"
          body: "The build and tests were successful."
          to: ${{ secrets.NOTIFICATION_EMAIL }}
          from: "GitHub Actions"
