name: Using GitHub Secrets

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  check-env-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - List files in working directory
        run: ls -la

      - name: Debug - Check if .env exists
        run: |
          if [ -f .env ]; then
            echo ".env file is present!"
          else
            echo "⚠️ .env file is missing!"
            exit 1
          fi

      - name: Upload .env file
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ github.workspace }}/.env
          include-hidden-files: true
